version: '3'

services: 
  short-api-db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment: 
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=shortapidb